apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"argocd-rbac-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-rbac-cm","namespace":"argocd"}}
  creationTimestamp: "2025-12-31T13:59:22Z"
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
  namespace: argocd
  resourceVersion: "2325385"
  uid: fe151093-7531-46f0-b66d-5da59af34eba
data:
  policy.csv: |
    p, role:org-admin, applications, *, */, allow
    p, role:org-admin, clusters, get, *, allow
    p, role:org-admin, repositories, get, *, allow
    p, role:org-admin, projects, get, *, allow

    p, role:demo-user, applications, get, default/*, allow
    p, role:demo-user, applications, sync, default/*, allow
    p, role:demo-user, applications, action/apps/Deployment/restart, default/*, allow


    g, user, role:admin
    g, jon, role:demo-user
   